---
# defaults file for kafka
kafka_version: 2.3.0
kafka_scala_version: 2.12
kafka_root_dir: /etc
kafka_dir: "{{ kafka_root_dir }}/kafka"
kafka_user: kafka
kafka_group: kafka
kafka_log_dirs: "{{ kafka_dir }}/logs"
kafka_broker_id: "{{ groups['kafka'].index(inventory_hostname)+1 }}"
kafka_listener_protocol: PLAINTEXT
kafka_listener_hostname: localhost
kafka_listener_port: 9092

kafka_advertised_listener_protocol: "{{ kafka_listener_protocol }}"
kafka_advertised_listener_hostname: "{{ kafka_listener_hostname }}"
kafka_advertised_listener_port: "{{ kafka_listener_port }}"
kafka_num_network_threads: 3
kafka_num_io_threads: 8
kafka_socket_send_buffer_bytes: 102400
kafka_socket_receive_buffer_bytes: 102400
kafka_socket_request_max_bytes: 104857600
kafka_num_partitions: 1
kafka_num_recovery_threads_per_data_dir: 1
kafka_offsets_topic_replication_factor: 1
kafka_transaction_state_log_replication_factor: 1
kafka_transaction_state_log_min_isr: 1
kafka_log_retention_hours: 168
kafka_log_segment_bytes: 107374182
kafka_log_retention_check_interval_ms: 300000
zooport: 2181
zookeeper_connect: "{{ zoo1 }}:{{ zooport }},{{ zoo2 }}:{{ zooport }}"
kafka_zookeeper_connection_timeout_ms: 6000
kafka_group_initial_rebalance_delay_ms: 0
kafka_zookeeper_data_dir: /data/zookeeper
kafka_zookeeper_client_port: 2181
kafka_zookeeper_max_client_cnxns: 0


