---
# tasks file for zabbix
- name: "Install zabbix repo package"
  yum:
    name: "https://repo.zabbix.com/zabbix/5.1/rhel/8/x86_64/zabbix-release-5.1-1.el8.noarch.rpm"
    state: present
  tags: zabbix

- name: "Ensure a list of zabbix packages installed"
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - zabbix-server-pgsql
    - zabbix-web-pgsql
    - zabbix-nginx-conf
    state: present
  tags: zabbix

- name: "Copy zabbix_server.conf to the targets"
  template:
    src: "zabbix/zabbix_server.conf.j2"
    dest: "{{ zabbix_data }}/zabbix_server.conf"
  become: true
  tags: zabbix

- name: "Copy nginx zabbix.conf to the targets"
  template:
    src: "nginx/zabbix.conf.j2"
    dest: "{{ confd }}/zabbix.conf"
  become: true
  tags: zabbix

- name: "Copy nginx.conf to the targets"
  template:
    src: "nginx/nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
  become: true
  tags: zabbix
  
- name: "Copy Zabbix_server.conf to the targets"
  template:
    src: "php-fpm/zabbix.conf.j2"
    dest: "/etc/php-fpm.d/zabbix.conf"
  become: true
  tags: zabbix

- name: "Enable and start zabbix service"
  systemd:
    name: zabbix-server
    enabled: yes
    state: restarted
    daemon_reload: yes
  tags: zabbix

- name: "Enable and start zabbix service"
  systemd:
    name: nginx
    enabled: yes
    state: restarted
    daemon_reload: yes
  tags: zabbix

- name: "Enable and start zabbix service"
  systemd:
    name: php-fpm
    enabled: yes
    state: restarted
    daemon_reload: yes
  tags: zabbix
  
