---
- hosts: productive
  remote_user: root
  tasks:
#   - name: Add repository Zabbix
#     command: rpm -ivh http://repo.zabbix.com/zabbix/4.4/rhel/8/x86_64/zabbix-release-4.4-1.el8.noarch.rpm
     
   - name: Install zabbix-agent
     yum:
        name: zabbix-agent
        state: latest
 
   - name: "Change zabbix_agentd.conf"
     lineinfile:
        dest: "/etc/zabbix/zabbix_agentd.conf"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backrefs: yes
        state: present
     with_items:
        - { regexp: 'LogFileSize=', line: 'LogFileSize=10' }
        - { regexp: 'Server=', line: 'Server=192.168.0.128' }
        - { regexp: 'ServerActive=', line: 'ServerActive=192.168.0.128' }
        - { regexp: 'Hostname=', line: '#Hostname=' }      
        - { regexp: 'HostMetadata=', line: 'HostMetadata="Linux"' }

   - name: Zabbix service enable
     command: systemctl enable zabbix-agent

   - name: Zabbix service start
     command: systemctl start zabbix-agent
     
   - name: Zabbix service restart
     command: systemctl restart zabbix-agent     
     

#        - { regexp: '^Hostname=', line: 'Hostname={{ test }}' }
#   - { regexp: '^HostnameItem=', line: 'HostnameItem={{ "system.hostname" }}' }
#   - name: Set some kernel parameters
#     lineinfile:
#       dest: /etc/sysctl.conf
#       regexp: "{{ item.regexp }}"
#       line: "{{ item.line }}"
#     with_items:
#       - { regexp: '^kernel.shmall', line: 'kernel.shmall = 2097152' }
#       - { regexp: '^kernel.shmmax', line: 'kernel.shmmax = 134217728' }
#       - { regexp: '^fs.file-max', line: 'fs.file-max = 65536' }